### PR TITLE
Update to latest version of scala/scala.js/outwatch

### PR DESCRIPTION
**Pull request by rohan-sircar**
Updated version to 0.0.10

Updated ScalaTest to 3.2.2
Updated scala version to 2.13.4
Updated scala.js version to 1.1.0
Updated to outwatch version to commit 676f94a
Added dependency to outwatch-utils
Updated scala.js bundler to 0.20.0
Updated sbt-microsites to 1.1.2
Removed obsolete scalac arguments

Updated Router class itself
- Now generic over effect type instead of being hardcoded to
cats.effect.IO
- Uses colibri.Observable instead of monix.Observable
- Added history events listener to update dom on back/forward
 button press

### CODE REVIEW

**Comment by rohan-sircar** [comment]
Usage - 
``` scala
sealed trait Page
  case object Home extends Page
  case object SomePage extends Page
  case class UserHome(id: Int) extends Page
  case object NotFound extends Page

  val router = AppRouter.create[Task, Page](NotFound) {
    case Root                       => Home
    case Root / "user" / IntVar(id) => UserHome(id)
    case Root / "page"              => SomePage
  }

  def resolver: PartialFunction[Page, VDomModifier] = {
    case Home         => div("hm")
    case SomePage     => div("page1")
    case UserHome(id) => div(s"User id: $id")
    case NotFound     => div("notfound")
  }

  def run(args: List[String]): UIO[ExitCode] = {
    router.store
      .flatMap(implicit store =>
        OutWatch
          .renderInto[Task](
            "#app",
            div(
              router.render(resolver),
              //watch for history events
              router.watch(),
              div(
                cls := "four wide column",
                ul(
                  li(router.link("/")("Home")),
                  li(router.link("/some-page")("SomePage")),
                  li(router.link("/user/0")("User Home")),
                  //simulate not found
                  li(router.link("/todomvc")("TodoMvc"))
                )
              )
            )
          )
      )
      .onErrorHandle(_.printStackTrace())
      .as(ExitCode.Success)
  }
```

**Comment by zakpatterson** [comment]
This is awesome! Thank you! I don't work much with outwatch anymore, but I would love to give it another look. So reviewing this might take me a day or two. I extremely appreciate it!

**Comment by rohan-sircar** [comment]
Great to hear! Outwatch looks promising, I would definitely recommend giving it another try.

p.s. by changing a few lines it is also possible to get hash paths working. Also, it would be nice to include the path variable extractors(like the IntVar here) as well. I could include them in another PR, I wasn't sure if I should include them in this PR or not,

**Comment by zakpatterson** [comment]
@rohan-sircar Thanks again for the PR. I took a pass at fixing a couple issues I ran into. Would you take a look at the build results and see if you can figure out what's going on? There's some scalajs linker error happening. Also it would be great if you could add your usage example pasted above in the docs. They're compiled with mdoc and checked as part of the build process.

**Comment by rohan-sircar** [comment]
Hi, thanks for reviewing! 

I looked around and found this issue - https://github.com/scala-js/scala-js/issues/4271.

I've found two ways to fix this -
1.  Downgrade scalajs-bundler from 0.20.0 to 0.19.0
2. Add a dummy @JSExportTopLevel method

Let me know which one you would prefer.

And yes I'll add the (full) usage example to the docs.

**Comment by zakpatterson** [comment]
Great, I think supporting most recent dependency versions is good, so option 2 I guess? Thanks for checking!

**Comment by rohan-sircar** [comment]
I thought mdocs are simple markdown. It's just like scala to typecheck everything, even the docs!

**Comment by zakpatterson** [comment]
> I thought mdocs are simple markdown. It's just like scala to typecheck everything, even the docs!

Yes! It is so nice. 

Not only that, it should be possible to have output from mdoc generated. Both as text and working js output. Don't go too far with docs for this PR. Just for your updates!

**Comment by rohan-sircar** [comment]
> Don't go too far with docs for this PR. Just for your updates!

Okay, I just added the usage example I gave here as you told me to right? The rest of the stuff was just to make it compile.

**Comment by zakpatterson** [comment]
Sounds great thanks a lot!

**Comment by zakpatterson** [comment]
Hey thanks so much for the PR @rohan-sircar!

**Comment by rohan-sircar** [comment]
Yay my first merged PR! Thanks for setting up the CI, it was very helpful.

**Pull request merged**
